from crewai import Agent, Crew, Process, Task
from tools.learning_tools import CodePlanningTool


def run_code_agent(llm, language, level, task_type, prompt, analysis):
    tool = CodePlanningTool()
    tool_guidance = tool._run(
        f"Language: {language}; level: {level}; request type: {task_type}; goal: {prompt}"
    )

    if task_type == "Explain a concept":
        task_goal = (
            "Explain the requested programming concept in simple language. Include a definition, "
            "syntax where relevant, a small example, line-by-line explanation, expected output, "
            "common mistakes, and 2-3 practice questions."
        )
        role = "Programming Concept Tutor"
    else:
        task_goal = (
            "Generate a solution that matches the user's requirements. Include readable code, "
            "helpful comments, sample input/output where relevant, a short explanation, and limitations. "
            "Do not claim that the code was executed or tested."
        )
        role = "Programming Code Assistant"

    agent = Agent(
        role=role,
        goal="Help the learner understand and produce useful, readable programming work.",
        backstory=(
            "You are a practical programming mentor. You adapt explanations to the learner's experience "
            "level and prefer small, understandable examples over unnecessary complexity."
        ),
        llm=llm,
        tools=[tool],
        allow_delegation=False,
        max_iter=4,
        verbose=False,
    )
    task = Task(
        description=(
            f"Request type: {task_type}\nProgramming language: {language}\n"
            f"Experience level: {level}\nUser request:\n{prompt}\n"
            f"Request analysis:\n{analysis}\n\n"
            f"{task_goal}\n\n"
            f"Tool guidance (generated by the Code Planning Tool):\n{tool_guidance}\n\n"
            "Use the attached Code Planning Tool if further language-specific guidance is needed. "
            "Put code inside correctly labelled Markdown code fences. Never include secrets, and never suggest "
            "executing untrusted code on a public server."
        ),
        expected_output="A well-structured learning explanation or code solution appropriate to the selected request type.",
        agent=agent,
    )
    crew = Crew(agents=[agent], tasks=[task], process=Process.sequential, verbose=False)
    return str(crew.kickoff())
