from crewai import Agent, Crew, Process, Task
from tools.learning_tools import RequestAnalysisTool


def run_requirement_analysis(llm, language, level, task_type, prompt, learning_days):
    tool = RequestAnalysisTool()
    tool_guidance = tool._run(
        f"Request type: {task_type}; language: {language}; level: {level}; "
        f"learning days: {learning_days}; user request: {prompt}"
    )
    agent = Agent(
        role="Programming Request Analyzer",
        goal="Turn the user's request into a clear, bounded programming task.",
        backstory=(
            "You are a careful technical mentor. You identify what the learner wants, "
            "their current level, constraints, and the best kind of output."
        ),
        llm=llm,
        tools=[tool],
        allow_delegation=False,
        max_iter=3,
        verbose=False,
    )
    task = Task(
        description=(
            "Analyze this request before another specialist works on it.\n"
            f"Request type: {task_type}\nLanguage: {language}\nExperience level: {level}\n"
            f"Available learning time: {learning_days} days\nUser request:\n{prompt}\n\n"
            f"Tool guidance (generated by the Request Analysis Tool):\n{tool_guidance}\n\n"
            "Use the attached Request Analysis Tool when additional clarification is useful. "
            "Then return a concise structured brief with: "
            "user goal, constraints, expected deliverable, level of explanation, assumptions, "
            "and anything that should not be invented."
        ),
        expected_output="A concise, structured request brief with clear requirements and constraints.",
        agent=agent,
    )
    crew = Crew(agents=[agent], tasks=[task], process=Process.sequential, verbose=False)
    return str(crew.kickoff())
