from crewai import Agent, Crew, Process, Task
from tools.learning_tools import RoadmapStructureTool


def run_roadmap_agent(llm, language, level, prompt, learning_days, analysis):
    tool = RoadmapStructureTool()
    tool_guidance = tool._run(
        f"Language: {language}; level: {level}; days: {learning_days}; goal: {prompt}"
    )
    agent = Agent(
        role="Personalized Learning Planner",
        goal="Create a realistic, progressive programming roadmap that matches the learner's level and time.",
        backstory=(
            "You are a patient programming instructor. You break complex subjects into small stages, "
            "include practice, and avoid skipping prerequisites."
        ),
        llm=llm,
        tools=[tool],
        allow_delegation=False,
        max_iter=3,
        verbose=False,
    )
    task = Task(
        description=(
            f"Create a personalized {learning_days}-day learning roadmap.\n"
            f"Language: {language}\nExperience level: {level}\nUser's goal: {prompt}\n"
            f"Request analysis:\n{analysis}\n\n"
            f"Tool guidance (generated by the Roadmap Structure Tool):\n{tool_guidance}\n\n"
            "Use the attached Roadmap Structure Tool if further structure guidance is needed. "
            "Use realistic daily or phase-based topics, measurable objectives, practice tasks, "
            "small projects, and a review day where appropriate. Do not promise mastery in an unrealistic time. "
            "Make the roadmap easy for a beginner to follow."
        ),
        expected_output=(
            "A clear roadmap with phases or days, topics, learning outcomes, exercises, mini-projects, "
            "and recommended next steps."
        ),
        agent=agent,
    )
    crew = Crew(agents=[agent], tasks=[task], process=Process.sequential, verbose=False)
    return str(crew.kickoff())
